# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: DONG Qihua's homepage
description: >- # this means to ignore newlines until "baseurl:"
  Personal homepage of DONG Qihua (Drax)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
favicon: /assets/img/icons/ic2.ico

# twitter_username: jekyllrb
email: dongqh078@gmail.com
github_username:  dddraxxx

# Extra settings
blog: false                 # Show blog tag and post list (on | off)
avatar: on               # Show avatar (on | off)
avatar_image: "assets/img/hhh.png"
avatar_description: "Trying to do better."
highlighter_theme: monokai  # Theme of the syntax_highlighter [base16 |
                            # colorful | github | gruvbox | molokai |
                            # monokai | pastie | thankful_eyes | tulip ]
toolbar_priority:        # Order of the items in the toolbar (except for blog and home)
  - About
nav:
  items: true

# Collections
collections:
  dropdown:
    output: false
  items:
    output: true
# ------------------------------------------------------------------------------

# Build settings
excerpt_separator: "<!--more-->"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme_base: "light" 
theme_switch: on
# theme: jekyll-theme-potato-hacker
# plugins:
#   - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
